# recipe.yaml
app: xcursor-generator
version: "1.0.0"

# Points to our neat package main() function
entrypoint: xcursor_generator:main

requirements:
  - PyQt6
  - win2xcur
  - Pillow

data:
  - xcursor_generator/
  - xcursor.png
  - xcursor.desktop
