name: Build AppImage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Standard version to ensure compatibility
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --onefile --name xcursor-generator main.py
      - name: Build AppImage
        uses: appimage-community/appimage-action@master
        with:
          args: --appdir AppDir --executable dist/xcursor-generator --output appimage
